package telas;

import controles.LoginController;
import controles.RelatorioController;
import controles.UsuarioController;
import ferramentas.CaixaDeDialogo;
import ferramentas.Consulta;
import java.sql.ResultSet;
import java.util.HashMap;
import modelos.Usuario;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author karoline.bratz
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Usuario objUsuario;
    UsuarioController objUsuarioControle;
    Character consulta;
    Consulta objConsulta = new Consulta();
    private static int usuarioNivel;
    LoginController login;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setExtendedState(TelaPrincipal.MAXIMIZED_BOTH);

    }

    public void importarNivel(Usuario user) {
        this.usuarioNivel = user.getNivel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCad = new javax.swing.JMenu();
        mnCadLivraria = new javax.swing.JMenuItem();
        mnCadLivro = new javax.swing.JMenuItem();
        mnCadFunc = new javax.swing.JMenuItem();
        mnCadCid = new javax.swing.JMenuItem();
        CadBairro = new javax.swing.JMenuItem();
        mnConsulta = new javax.swing.JMenu();
        mnConsLivraria = new javax.swing.JMenuItem();
        mnConsLivros = new javax.swing.JMenuItem();
        mnConsFunc = new javax.swing.JMenuItem();
        mnConsCid = new javax.swing.JMenuItem();
        mnConsBairro = new javax.swing.JMenuItem();
        mnRelatorio = new javax.swing.JMenu();
        mnRelLivraria = new javax.swing.JMenuItem();
        mnRelLogin = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenu();

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mnCad.setText("Cadastros");

        mnCadLivraria.setText("Livraria");
        mnCadLivraria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadLivrariaActionPerformed(evt);
            }
        });
        mnCad.add(mnCadLivraria);

        mnCadLivro.setText("Livro");
        mnCadLivro.setEnabled(false);
        mnCadLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadLivroActionPerformed(evt);
            }
        });
        mnCad.add(mnCadLivro);

        mnCadFunc.setText("Funcionário");
        mnCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadFuncActionPerformed(evt);
            }
        });
        mnCad.add(mnCadFunc);

        mnCadCid.setText("Cidade");
        mnCadCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadCidActionPerformed(evt);
            }
        });
        mnCad.add(mnCadCid);

        CadBairro.setText("Bairro");
        CadBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadBairroActionPerformed(evt);
            }
        });
        mnCad.add(CadBairro);

        jMenuBar1.add(mnCad);

        mnConsulta.setText("Consulta");

        mnConsLivraria.setText("Livraria");
        mnConsLivraria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsLivrariaActionPerformed(evt);
            }
        });
        mnConsulta.add(mnConsLivraria);

        mnConsLivros.setText("Livros");
        mnConsLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsLivrosActionPerformed(evt);
            }
        });
        mnConsulta.add(mnConsLivros);

        mnConsFunc.setText("Funcionário");
        mnConsFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsFuncActionPerformed(evt);
            }
        });
        mnConsulta.add(mnConsFunc);

        mnConsCid.setText("Cidade");
        mnConsCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsCidActionPerformed(evt);
            }
        });
        mnConsulta.add(mnConsCid);

        mnConsBairro.setText("Bairro");
        mnConsBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsBairroActionPerformed(evt);
            }
        });
        mnConsulta.add(mnConsBairro);

        jMenuBar1.add(mnConsulta);

        mnRelatorio.setText("Relatório");
        mnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelatorioActionPerformed(evt);
            }
        });

        mnRelLivraria.setText("Livraria");
        mnRelLivraria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelLivrariaActionPerformed(evt);
            }
        });
        mnRelatorio.add(mnRelLivraria);

        mnRelLogin.setText("Login");
        mnRelLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelLoginActionPerformed(evt);
            }
        });
        mnRelatorio.add(mnRelLogin);

        jMenuBar1.add(mnRelatorio);

        mnSair.setText("Sair");
        mnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnSairMousePressed(evt);
            }
        });
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(634, 478));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnCadLivrariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadLivrariaActionPerformed
        CadastroLivraria frame = new CadastroLivraria();
        frame.setVisible(true);
        objConsulta.setConsulta('n');
    }//GEN-LAST:event_mnCadLivrariaActionPerformed

    private void mnCadLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadLivroActionPerformed
        // CadastroLivro frame = new CadastroLivro();
        // frame.setVisible(true);
        objConsulta.setConsulta('n');
    }//GEN-LAST:event_mnCadLivroActionPerformed


    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        Login frame = new Login();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnSairActionPerformed

    private void mnConsLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsLivrosActionPerformed
        // CadastroLivro frame = new CadastroLivro();
        // frame.setVisible(true);
        objConsulta.setConsulta('s');
    }//GEN-LAST:event_mnConsLivrosActionPerformed

    private void mnConsLivrariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsLivrariaActionPerformed
        CadastroLivraria frame = new CadastroLivraria();
        frame.setVisible(true);
        objConsulta.setConsulta('s');

    }//GEN-LAST:event_mnConsLivrariaActionPerformed

    private void mnCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadFuncActionPerformed
        CadastroFuncionario frame = new CadastroFuncionario();
        frame.setVisible(true);
        objConsulta.setConsulta('n');
    }//GEN-LAST:event_mnCadFuncActionPerformed

    private void mnCadCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadCidActionPerformed
        CadastroCidade frame = new CadastroCidade();
        frame.setVisible(true);
        objConsulta.setConsulta('f');
    }//GEN-LAST:event_mnCadCidActionPerformed

    private void mnConsFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsFuncActionPerformed
        CadastroFuncionario frame = new CadastroFuncionario();
        frame.setVisible(true);
        objConsulta.setConsulta('s');
    }//GEN-LAST:event_mnConsFuncActionPerformed

    private void mnConsCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsCidActionPerformed
        CadastroCidade frame = new CadastroCidade();
        frame.setVisible(true);
        ///consulta = true;
    }//GEN-LAST:event_mnConsCidActionPerformed

    private void CadBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadBairroActionPerformed
        CadastroBairro frame = new CadastroBairro();
        frame.setVisible(true);
        objConsulta.setConsulta('n');
    }//GEN-LAST:event_CadBairroActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /*
        1-administrador
        2-gerente
        3-funcionário
        4-cliente
         */
        // String user = usu
        //objUsuarioController.buscar(Usuario.getLogin);

        if (usuarioNivel == 1) {

        } else if (usuarioNivel == 2) {
            mnCadFunc.setVisible(false);
        } else if (usuarioNivel == 3) {
            mnCadLivraria.setVisible(false);
            mnCadFunc.setVisible(false);
        } else if (usuarioNivel == 4) {
            mnCad.setVisible(false);
            mnConsFunc.setVisible(false);
            mnConsCid.setVisible(false);
        }

    }//GEN-LAST:event_formWindowOpened

    private void mnConsBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsBairroActionPerformed
        CadastroBairro frame = new CadastroBairro();
        frame.setVisible(true);
        objConsulta.setConsulta('s');
    }//GEN-LAST:event_mnConsBairroActionPerformed

    private void mnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelatorioActionPerformed

    }//GEN-LAST:event_mnRelatorioActionPerformed

    private void mnRelLivrariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelLivrariaActionPerformed
        try {
            String wSelect = " SELECT l.id_livraria as Livraria, c.nome as Cidade, b.nome as Bairro"
                    + " FROM livraria l, cidade c, bairro b"
                    + " WHERE l.id_bairro = b.id_bairro"
                    + " AND l.id_cidade = c.id_cidade"
                    + " GROUP BY l.id_livraria, c.nome, b.nome"
                    + " ORDER BY l.id_livraria";

            RelatorioController objRelController = new RelatorioController();
            ResultSet resultSet = objRelController.buscarRelatorio(wSelect);//Buscar os dados do relatório

            JRResultSetDataSource relResult = new JRResultSetDataSource(resultSet);//Passa um resultSet para a fonte de dados do relatório
            JasperPrint jpPrint = JasperFillManager.fillReport("iReport/RelatorioLivraria1.jasper", new HashMap(), relResult);//Prepara o relatório para ser impresso, recebe o gerenciador JASPER
            JasperViewer jpViewer = new JasperViewer(jpPrint, false); //
            jpViewer.setVisible(true);//abre o relatório para visualização
            jpViewer.toFront();//define o form a frente da aplicação

        } catch (JRException ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_mnRelLivrariaActionPerformed

    private void mnSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSairMousePressed

        Login frame = new Login();
        frame.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_mnSairMousePressed

    private void mnRelLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelLoginActionPerformed
        try {
            String wSelect = " SELECT nivel, nome, login "
                    + " FROM usuario "
                    + " GROUP BY nivel";

            RelatorioController objRelController = new RelatorioController();
            ResultSet resultSet = objRelController.buscarRelatorio(wSelect);//Buscar os dados do relatório

            JRResultSetDataSource relResult = new JRResultSetDataSource(resultSet);//Passa um resultSet para a fonte de dados do relatório
            JasperPrint jpPrint = JasperFillManager.fillReport("iReport/RelatorioLivraria.jasper", new HashMap(), relResult);//Prepara o relatório para ser impresso, recebe o gerenciador JASPER
            JasperViewer jpViewer = new JasperViewer(jpPrint, false); //
            jpViewer.setVisible(true);//abre o relatório para visualização
            jpViewer.toFront();//define o form a frente da aplicação

        } catch (JRException ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
        
    }//GEN-LAST:event_mnRelLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadBairro;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mnCad;
    private javax.swing.JMenuItem mnCadCid;
    private javax.swing.JMenuItem mnCadFunc;
    private javax.swing.JMenuItem mnCadLivraria;
    private javax.swing.JMenuItem mnCadLivro;
    private javax.swing.JMenuItem mnConsBairro;
    private javax.swing.JMenuItem mnConsCid;
    private javax.swing.JMenuItem mnConsFunc;
    private javax.swing.JMenuItem mnConsLivraria;
    private javax.swing.JMenuItem mnConsLivros;
    private javax.swing.JMenu mnConsulta;
    private javax.swing.JMenuItem mnRelLivraria;
    private javax.swing.JMenuItem mnRelLogin;
    private javax.swing.JMenu mnRelatorio;
    private javax.swing.JMenu mnSair;
    // End of variables declaration//GEN-END:variables
}
