/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controles.CidadeController;
import controles.LivrariaController;
import ferramentas.CaixaDeDialogo;
import ferramentas.Combos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelos.Livraria;

/**
 *
 * @author USER
 */
public class CadastroLivraria extends javax.swing.JFrame {
    
    Livraria objLivraria;
    LivrariaController objLivrariaControle;
    Combos cbCombosCidade;
    Combos cbCombosBairro;
    /**
     * Creates new form CadastroLivraria
     */
    public CadastroLivraria() {
        initComponents();
        atualizarTabela();
        preencherCombos();
    }
    
         private void atualizarTabela(){
        try{
            
            objLivrariaControle = new LivrariaController(null, jtbLivraria);
            objLivrariaControle.preencher();
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("ERRO:" + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbCidade = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbLivraria = new javax.swing.JTable();
        cbBairro = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("CIDADE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        cbCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCidadeItemStateChanged(evt);
            }
        });
        cbCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(cbCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 189, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("BAIRRO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        lblId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblId.setText("ID");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("CADASTRO DE LIVRARIA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 99, -1));

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 99, -1));

        jtbLivraria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbLivraria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbLivrariaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtbLivraria);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 265, 670, 150));

        cbBairro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 191, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        limparTela();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        try{
            boolean retorno;
            //validar os campos
            if(cbBairro.getSelectedIndex() == 0 || cbCidade.getSelectedIndex() == 0){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Informe uma livraria ou cidade corretamente", 'a');
                return;
            }

            objLivraria = new Livraria();
            Combos c = (Combos) cbCidade.getSelectedItem();
            String codCidade = c.getCodigo();
            Combos c2 = (Combos) cbBairro.getSelectedItem();
            String codBairro = c2.getCodigo();
            objLivraria.setId_cidade(Integer.parseInt(codCidade));
            objLivraria.setId_bairro(Integer.parseInt(codBairro));
            if(!lblId.getText().equals("ID")){
                objLivraria.setId_livraria(Integer.parseInt(lblId.getText()));
                objLivrariaControle = new LivrariaController(objLivraria, null);
                retorno = objLivrariaControle.alterar();
            }else{
                objLivrariaControle = new LivrariaController(objLivraria, null);
   
                retorno = objLivrariaControle.incluir();
            }
            
            if(retorno = true){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Registro salvo");
            }else{
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao tentar salvar");
            }
            
            atualizarTabela();

        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao tentar incluir");
            System.out.println("ERRO: " + ex.getMessage().toString());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jtbLivrariaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbLivrariaMousePressed
        try{
            
            int linhaSelecionada = jtbLivraria.getSelectedRow();//pega a linha selecionada
            String codigo = jtbLivraria.getModel().getValueAt(linhaSelecionada, 0).toString(); // Primeira coluna da linha
           

            //Verifica se clicou na coluna 2 = EXCLUIR
            if(jtbLivraria.getSelectedColumn() == 3){
                try{
                    
                    boolean wPergunta = CaixaDeDialogo.obterinstancia().pedirConfirmacao("Tem certeza de que deseja excluir?","",'p');
                    if (wPergunta == true){
                        lblId.setText(codigo);
                        objLivraria = new Livraria();
                        objLivraria.setId_livraria(Integer.parseInt(lblId.getText()));
                        
                        objLivrariaControle = new LivrariaController(objLivraria, null);
                        boolean wControle = objLivrariaControle.excluir();
                        if (wControle){
                            CaixaDeDialogo.obterinstancia().exibirMensagem("Excluído com Sucesso!");
                        }else{
                            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao excluir!");
                        }
                    }

                }catch(Exception ex){
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
                }
            }else {
                objLivrariaControle = new LivrariaController(objLivraria, null);
                objLivraria = objLivrariaControle.buscar(codigo);
                
                if (objLivraria != null) {
                    lblId.setText(String.valueOf(objLivraria.getId_livraria()));
                    cbCombosBairro.SetaComboBox(String.valueOf(objLivraria.getId_bairro()));
                }
            }
        
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem(ex.getMessage(), 'e');
        }
        atualizarTabela();
    }//GEN-LAST:event_jtbLivrariaMousePressed

    private void cbCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCidadeActionPerformed
       try {
           
        atualizarComboBairro();
       } catch(Exception e) {
           System.out.println("");
       }
    }//GEN-LAST:event_cbCidadeActionPerformed

    private void cbCidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCidadeItemStateChanged
                 
        try {
            if (cbCidade.getSelectedIndex() > 0) {
                
            Combos c = (Combos) cbCidade.getSelectedItem();
            String codCidade = c.getCodigo();
        
            
            cbCombosBairro.PreencheCombo("SELECT b.id_bairro, b.nome FROM bairro b, cidade c WHERE b.id_cidade = c.id_cidade AND c.id_cidade =" + codCidade);
            cbCombosBairro.SetaComboBox(codCidade);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CadastroLivraria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbCidadeItemStateChanged
        private void atualizarComboBairro() {
        
        
            }
        private void preencherCombos() {
        try {
            
            cbCombosCidade = new Combos(cbCidade);        
            cbCombosCidade.PreencheCombo("SELECT id_cidade, nome FROM cidade WHERE data_exclusao IS NULL");
            
            cbCombosBairro = new Combos(cbBairro);        
            cbCombosBairro.PreencheCombo("SELECT id_bairro, nome FROM bairro WHERE data_exclusao IS NULL");
            
            cbBairro.setSelectedIndex(1);
            cbCidade.setSelectedIndex(1);
            
        } catch (Exception e) {
            CaixaDeDialogo.obterinstancia().exibirMensagem(e.getMessage());
        }
    }
        
                private void limparTela(){
        try{
            lblId.setText("ID");
            cbBairro.setSelectedIndex(1);
            cbCidade.setSelectedIndex(1);
           
            btnSalvar.setEnabled(true);
            
            atualizarTabela();
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
        }
    }
                
        private void preencherCampos(){
        try{
            lblId.setText(String.valueOf(objLivraria.getId_livraria()));
            btnSalvar.setEnabled(true);
            
            atualizarTabela();
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
        }
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLivraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLivraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLivraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLivraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLivraria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbBairro;
    private javax.swing.JComboBox<String> cbCidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbLivraria;
    private javax.swing.JLabel lblId;
    // End of variables declaration//GEN-END:variables
}
